// Code generated by github.com/DoNotPayHQ/gqlgen-fork, DO NOT EDIT.

package dataloader

type Address struct {
	ID      int    `json:"id"`
	Street  string `json:"street"`
	Country string `json:"country"`
}

type Item struct {
	Name string `json:"name"`
}
