// Code generated by github.com/DoNotPayHQ/gqlgen-fork, DO NOT EDIT.

package model

import (
	"github.com/DoNotPayHQ/gqlgen-fork/example/scalars/external"
)

type Address struct {
	ID       external.ObjectID `json:"id"`
	Location *Point            `json:"location"`
}
